### ISSUE TITLE
Add tests for profile class

### ISSUE THREAD

**Issue by ktraina** [ktraina/GAKK#16]
- Multiple users should not be able to have the same username
- All fields should start out as nil
- User cannot create/edit profile is any field values are nil (excluding the address fields)
- Postal code should only be 5 digits
- Postal code should not be negative
- Can only enter integer for postal code
- Make sure input data does not break system

**Comment by keirl** [comment]
I am adding special characters to city and street address.

**Comment by audesilva** [comment]
Currently if a user enter a negative zip-code then the profile can be saved.
